version: '2'
services:
  client:
    build: ./client
    ports:
      - '3000:3000'
    links:
      - server
    environment:
      PORT: 3000
      API_BASE_URL: http://server:4000/graphql
  server:
    build: ./server
    restart: always
    ports:
      - '4000:4000'
    environment:
      PORT: 4000